In [38]:
import pandas as pd
import os
import time
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv('./movie_data.csv')
print df.head()
print
print df['review'].head(20)[15]
print 
print df.loc[15,'review']


count = CountVectorizer()

                                              review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0

I saw this movie on the strength of the single positive review and I can only imagine that guy is a shill.<br /><br />The acting of the female lead is actually quite good, but the entire film is just so excruciatingly boring I could hardly bear to sit through it. This is the very definition of dullness.<br /><br />So far, this film is rated as 8 out of 10 on 7 votes. That must mean the director, director's girlfriend, producer, actress and drinking buddies have given their own film a 10.<br /><br />For the rest of you, who simply want to be entertained or enjoy a good story, avoid this.<br /><br />This man o

In [11]:
docs = np.array([
'The sun is shining',
'The weather is sweet',
'The sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)
print bag
print(count.vocabulary_)
print(bag.toarray())

  (0, 5)	1
  (0, 3)	1
  (0, 1)	1
  (0, 2)	1
  (1, 5)	1
  (1, 1)	1
  (1, 6)	1
  (1, 4)	1
  (2, 5)	2
  (2, 3)	1
  (2, 1)	2
  (2, 2)	1
  (2, 6)	1
  (2, 4)	1
  (2, 0)	1
{u'and': 0, u'weather': 6, u'sweet': 4, u'sun': 3, u'is': 1, u'the': 5, u'shining': 2}
[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [12]:
#tf-idf: term frequency - inverse document frequency ( bag of words model)
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[ 0.    0.43  0.56  0.56  0.    0.43  0.  ]
 [ 0.    0.43  0.    0.    0.56  0.43  0.56]
 [ 0.4   0.48  0.31  0.31  0.31  0.48  0.31]]


In [49]:
# cleaning the text datab
df.loc[0, 'review'][-50:]
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower())
    return text

print preprocessor(df.loc[0, 'review'][-50:])
print preprocessor("</a>This :) is :( a test :-)!")

zation my vote is seven title brazil not available
zation my vote is seven title brazil not available
this is a test 


In [47]:
df['review'] = df['review'].apply(preprocessor)
print df.loc[0, 'review'][-50:]

zation my vote is seven title brazil not available
